query Blog {
  posts(where: {categoryName: "Blog", status: PUBLISH}) {
    nodes {
      title
      author {
        node {
          name
        }
      }
      excerpt
      featuredImage {
        node{
          mediaItemUrl
        }
      }
      slug
      date
    }
  }
}