query Article($id: ID!) {
  post(id: $id, idType: SLUG) {
    title
    content
    date
    excerpt
    slug
    author {
      node {
        name
      }
    }
    featuredImage {
      node {
        mediaItemUrl
      }
    }
    seo {
      metaDesc
    }
  }
}