query Article($id: ID!) {
  post(id: $id, idType: SLUG) {
    title
    content
    date
    excerpt
    slug
    author {
      name
    }
    featuredImage {
      mediaItemUrl
    }
    seo {
      metaDesc
    }
  }
}